name: Directory Structure Update

on: [push]

jobs:
  update-directory-structure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "2755631915@qq.com"
        git config --global user.name "hdb123456"
        # 生成目录结构
        tree > directory.md

    - name: Update README.md
      run: |
        echo "# Directory Structure" > README.md
        echo "" >> README.md
        echo "Generated at: $(date -R)" >> README.md
        echo "" >> README.md
        cat directory.md >> README.md
        git add README.md
        git commit -m "Update directory structure in README"

    - name: Push Changes
      run: |
        git push origin main
